# Generated by Django 5.2.7 on 2025-12-17 14:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(blank=True, default='', editable=False, max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]+$', 'Utilisez lettres majuscules, chiffres et tirets.')])),
                ('code_prefix', models.CharField(blank=True, default='', help_text='Préfixe utilisé dans le code des dons (ex: AMIS, ONG01).', max_length=12)),
                ('raison_sociale', models.CharField(help_text='Raison sociale / Nom du donateur', max_length=200)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('courriel', models.EmailField(blank=True, default='', max_length=254)),
                ('remarque', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Donateur',
                'verbose_name_plural': 'Donateurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(blank=True, editable=False, help_text='Généré automatiquement par le système.', max_length=20, unique=True)),
                ('raison_sociale', models.CharField(help_text="Nom légal de l'entreprise ou nom du fournisseur.", max_length=255)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('numero', models.CharField(blank=True, default='', help_text='Numéro de téléphone.', max_length=30)),
                ('courriel', models.EmailField(blank=True, default='', max_length=254)),
                ('ninea', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('code_prefix', models.CharField(blank=True, default='', help_text='Préfixe utilisé dans les codes documents (ex: ELECTRO). Sera auto-généré si vide.', max_length=20)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=128, unique=True, verbose_name='Libellé')),
                ('responsable', models.CharField(max_length=128, verbose_name='Responsable')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['code', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=16, unique=True, verbose_name='Abréviation')),
                ('libelle', models.CharField(max_length=64, unique=True, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['abreviation', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, verbose_name='Année')),
                ('date_debut', models.DateField(editable=False, verbose_name='Date de début')),
                ('date_fin', models.DateField(editable=False, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOS', 'Clos')], default='OUVERT', max_length=10, verbose_name='Statut')),
                ('code', models.CharField(editable=False, max_length=16, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['-annee'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'OUVERT')), fields=('statut',), name='unique_exercice_ouvert')],
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=16, unique=True, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=128, unique=True, verbose_name='Nom')),
                ('type_lieu', models.CharField(choices=[('DEPOT', 'Dépôt / Magasin'), ('BUREAU', 'Bureau / Service')], default='DEPOT', max_length=10, verbose_name='Type de lieu')),
                ('responsable', models.CharField(blank=True, default='', max_length=128, verbose_name='Responsable')),
                ('localisation', models.CharField(blank=True, default='', max_length=128, verbose_name='Localisation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lieux', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Dépôt / Bureau',
                'verbose_name_plural': 'Dépôts / Bureaux',
                'ordering': ['identifiant', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='FournisseurSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('type_doc', models.CharField(choices=[('ACH', 'Achat'), ('RET', 'Retour fournisseur')], max_length=3)),
                ('next_seq', models.PositiveIntegerField(default=1)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='core.fournisseur')),
            ],
            options={
                'verbose_name': 'Séquence fournisseur',
                'verbose_name_plural': 'Séquences fournisseurs',
                'indexes': [models.Index(fields=['fournisseur', 'annee', 'type_doc'], name='core_fourni_fournis_89fa62_idx')],
                'unique_together': {('fournisseur', 'annee', 'type_doc')},
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('ACH', 'ACH'), ('ENT', 'ENT'), ('SOR', 'SOR'), ('TRA', 'TRA'), ('AJU', 'AJU'), ('INV', 'INV'), ('MAT', 'MAT'), ('PRJ', 'PRJ'), ('REF', 'REF'), ('MNT', 'MNT'), ('BE', 'BE'), ('BS', 'BS'), ('BT', 'BT'), ('PV', 'PV')], max_length=16, verbose_name='Type de pièce')),
                ('dernier_numero', models.PositiveIntegerField(default=0, verbose_name='Dernier numéro')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='core.exercice', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Séquence',
                'verbose_name_plural': 'Séquences',
                'indexes': [models.Index(fields=['type_piece', 'exercice'], name='core_sequen_type_pi_d85b59_idx')],
                'unique_together': {('type_piece', 'exercice')},
            },
        ),
    ]
