# Generated by Django 5.2.7 on 2025-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('MINISTRY', 'Ministère'), ('SCHOOL', 'École / Université'), ('PARTNER', 'Partenaire'), ('OTHER', 'Autre')], max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('acronym', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Structure source',
                'verbose_name_plural': 'Structures sources',
                'ordering': ['source_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'name'), name='uniq_external_source_type_name')],
            },
        ),
    ]
