# Generated by Django 5.2.7 on 2026-02-27 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pendingrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrecord',
            name='data',
            field=models.JSONField(verbose_name='Données (JSON)'),
        ),
        migrations.AlterField(
            model_name='pendingrecord',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='pendingrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Révisé le'),
        ),
        migrations.AlterField(
            model_name='pendingrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pending', to=settings.AUTH_USER_MODEL, verbose_name='Révisé par'),
        ),
        migrations.AlterField(
            model_name='pendingrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='pendingrecord',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom affiché'),
        ),
    ]
