# Generated by Django 5.2.7 on 2026-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsource',
            name='source_type',
            field=models.CharField(choices=[('MINISTRY', 'Ministère'), ('SCHOOL', 'École / Université'), ('PARTNER', 'Partenaire'), ('LEGS', 'Legs'), ('DOTATION', 'Dotation'), ('OTHER', 'Autre')], max_length=16),
        ),
    ]
