# Generated by Django 5.2.7 on 2026-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_legsentry_dotation_lignedotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotation',
            name='code',
            field=models.CharField(blank=True, default='', max_length=60, unique=True),
        ),
    ]
