# Generated by Django 5.2.7 on 2026-03-04 22:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_externalsource_source_type'),
        ('purchasing', '0004_alter_dotation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotations', to='core.service', verbose_name='Service bénéficiaire'),
        ),
        migrations.AddField(
            model_name='dotation',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('ANNULE', 'Annulée')], db_index=True, default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='dotation',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Généré automatiquement : DOT-AAAA-NNNNN', max_length=60, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='dotation',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='N° document de référence'),
        ),
        migrations.AlterField(
            model_name='dotation',
            name='total_value',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), editable=False, max_digits=16, verbose_name='Valeur totale'),
        ),
        migrations.AlterField(
            model_name='dotation',
            name='type_dotation',
            field=models.CharField(blank=True, choices=[('1ER_GROUPE', '1er groupe — biens durables (affectation)'), ('2EME_GROUPE', '2e groupe — consommables (sortie définitive)'), ('MIXTE', 'Mixte — 1er et 2e groupe')], default='', editable=False, help_text='Calculé automatiquement selon les groupes des matières distribuées.', max_length=20, verbose_name='Type de dotation'),
        ),
        migrations.AlterField(
            model_name='lignedotation',
            name='total_ligne',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=16, verbose_name='Total ligne'),
        ),
    ]
