# Generated by Django 5.2.7 on 2025-12-17 14:03

import django.db.models.deletion
import django.utils.timezone
import inventory.models.operation_sortie
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventaireMatiere',
            fields=[
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaire (matières)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.matiere',),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', 'Ajustement')], max_length=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cout_unitaire', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('cout_total', models.DecimalField(decimal_places=6, editable=False, max_digits=16)),
                ('is_stock_initial', models.BooleanField(default=False, help_text="Cocher uniquement pour la saisie initiale d'exercice.")),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('source_doc_type', models.CharField(blank=True, default='', max_length=30)),
                ('source_doc_id', models.PositiveIntegerField(blank=True, null=True)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_depot', to='core.depot')),
                ('destination_depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_destination', to='core.depot')),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='core.exercice')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='catalog.matiere')),
                ('source_depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_source', to='core.depot')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EntreeStock',
            fields=[
            ],
            options={
                'verbose_name': 'Entrée de stock',
                'verbose_name_plural': 'Entrées de stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.mouvementstock',),
        ),
        migrations.CreateModel(
            name='SortieStock',
            fields=[
            ],
            options={
                'verbose_name': 'Sortie de stock',
                'verbose_name_plural': 'Sorties de stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.mouvementstock',),
        ),
        migrations.CreateModel(
            name='StockInitial',
            fields=[
            ],
            options={
                'verbose_name': 'Stock initial',
                'verbose_name_plural': 'Stocks initiaux',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.mouvementstock',),
        ),
        migrations.CreateModel(
            name='OperationSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', help_text='Généré automatiquement, ex : SO-2025-00001', max_length=40, unique=True, verbose_name='Code')),
                ('type_sortie', models.CharField(choices=[('REFORME_DESTRUCTION', 'Réforme / destruction définitive'), ('PERTE_VOL_DEFICIT', 'Pertes, vols, destructions accidentelles, déficit d’inventaire'), ('CONSOMMATION_2E_GROUPE', 'Consommation de matières du 2ᵉ groupe'), ('CERTIFICAT_ADMIN', 'Sortie justifiée par certificat administratif'), ('FIN_GESTION', 'Opérations de fin de gestion')], default='REFORME_DESTRUCTION', max_length=40, verbose_name='Type de sortie')),
                ('date_sortie', models.DateField(default=django.utils.timezone.now, verbose_name='Date de sortie')),
                ('motif_principal', models.CharField(blank=True, default='', help_text='Ex : Casse importante, réforme matériel obsolète, etc.', max_length=200, verbose_name='Motif principal / libellé interne')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Description / Observations')),
                ('numero_document', models.CharField(blank=True, default='', help_text='Numéro de PV / certificat / document justificatif, si applicable.', max_length=80, verbose_name='Numéro de document')),
                ('fichier_document', models.FileField(blank=True, help_text='Scan du PV, certificat ou autre pièce justificative.', null=True, upload_to=inventory.models.operation_sortie._upload_document_path, verbose_name='Pièce justificative')),
                ('total_valeur', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='Valeur totale')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_sortie', to='core.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Opération de sortie de stock (définitive)',
                'verbose_name_plural': 'Opérations de sortie de stock (définitives)',
                'ordering': ['-date_sortie', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneOperationSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='Quantité à sortir')),
                ('prix_unitaire', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Utilisé pour valoriser la sortie (optionnel).', max_digits=14, verbose_name='Prix unitaire (valorisation)')),
                ('total_ligne', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='Total ligne')),
                ('commentaire', models.CharField(blank=True, default='', max_length=255, verbose_name='Commentaire')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_operation_sortie', to='catalog.matiere', verbose_name='Matière')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventory.operationsortie', verbose_name='Opération de sortie')),
            ],
            options={
                'verbose_name': "Ligne d'opération de sortie de stock",
                'verbose_name_plural': "Lignes d'opération de sortie de stock",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OperationTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', help_text='Généré automatiquement, ex : TR-2025-00001', max_length=40, unique=True, verbose_name='Code')),
                ('date_operation', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('motif', models.CharField(choices=[('AFFECTATION', 'Affectation à un bureau/service'), ('MUTATION', "Mutation interne (changement d'emplacement)"), ('RETOUR', 'Retour vers magasin'), ('AUTRE', 'Autre')], default='AFFECTATION', max_length=20, verbose_name='Motif')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / Observations')),
                ('total_valeur', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='Valeur totale')),
                ('depot_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_transfert_entrantes', to='core.depot', verbose_name='Dépôt destination')),
                ('depot_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_transfert_sortantes', to='core.depot', verbose_name='Dépôt source')),
            ],
            options={
                'verbose_name': 'Opération de transfert (Affectation/Mutation)',
                'verbose_name_plural': 'Opérations de transfert (Affectations/Mutations)',
                'ordering': ['-date_operation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneOperationTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='Quantité')),
                ('cout_unitaire', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14, verbose_name='Coût unitaire (optionnel)')),
                ('total_ligne', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='Total ligne')),
                ('commentaire', models.CharField(blank=True, default='', max_length=255, verbose_name='Commentaire')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_operation_transfert', to='catalog.matiere', verbose_name='Matière')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventory.operationtransfert', verbose_name='Opération')),
            ],
            options={
                'verbose_name': 'Ligne opération transfert',
                'verbose_name_plural': 'Lignes opération transfert',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockCourant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('cump', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('stock_initial_qte', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('stock_initial_cu', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_courants', to='core.depot')),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_courants', to='core.exercice')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_courants', to='catalog.matiere')),
            ],
            options={
                'verbose_name': 'État de stock',
                'verbose_name_plural': 'États de stock',
            },
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['matiere', 'depot'], name='inventory_m_matiere_fdd6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['source_doc_type', 'source_doc_id'], name='inventory_m_source__cd7937_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['exercice', 'matiere', 'depot'], name='inventory_m_exercic_61bb49_idx'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_stock_initial', True), ('type', 'ENTREE')), fields=('exercice', 'matiere', 'depot'), name='uniq_stock_initial_par_exercice_matiere_depot'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.UniqueConstraint(fields=('source_doc_type', 'source_doc_id'), name='uniq_mvt_stock_source_doc'),
        ),
        migrations.AddIndex(
            model_name='stockcourant',
            index=models.Index(fields=['exercice', 'matiere', 'depot'], name='inventory_s_exercic_a2830e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcourant',
            index=models.Index(fields=['matiere', 'depot'], name='inventory_s_matiere_d90789_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcourant',
            unique_together={('exercice', 'matiere', 'depot')},
        ),
    ]
