# Generated by Django 5.2.7 on 2026-02-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_source_doc_type_max60'),
        ('inventory', '0002_stockcourantproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='exercice',
            field=models.ForeignKey(blank=True, help_text='Renseigné automatiquement via la date si possible.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='core.exercice'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='is_stock_initial',
            field=models.BooleanField(default=False, help_text='Auto: la 1ère ENTREE (par exercice, matière, dépôt) est marquée stock initial.'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='source_doc_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
