# Generated by Django 5.2.7 on 2026-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_source_doc_type_max60'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsortie',
            name='type_sortie',
            field=models.CharField(choices=[('REFORME_DESTRUCTION', 'Réforme / destruction définitive'), ('PERTE_VOL_DEFICIT', 'Pertes, vols, destructions accidentelles, déficit d’inventaire'), ('CONSOMMATION_2E_GROUPE', 'Consommation de matières du 2ᵉ groupe'), ('CERTIFICAT_ADMIN', 'Sortie justifiée par certificat administratif'), ('FIN_GESTION', 'Opérations de fin de gestion'), ('VENTE', 'Vente')], default='REFORME_DESTRUCTION', max_length=40, verbose_name='Type de sortie'),
        ),
    ]
