# Generated by Django 5.2.7 on 2026-03-04 22:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0007_alter_externalsource_source_type'),
        ('inventory', '0004_alter_operationsortie_type_sortie'),
        ('purchasing', '0004_alter_dotation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', 'Ajustement'), ('AFFECTATION', 'Affectation (1er groupe)')], max_length=12),
        ),
        migrations.CreateModel(
            name='FicheAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', help_text='Généré automatiquement : FA-AAAA-NNNNN', max_length=30, unique=True, verbose_name='Code')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Quantité')),
                ('beneficiaire', models.CharField(max_length=200, verbose_name='Agent bénéficiaire')),
                ('date_affectation', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'affectation")),
                ('statut', models.CharField(choices=[('AFFECTE', 'Affecté'), ('REINTEGRE', 'Réintégré au dépôt'), ('REFORME', 'Réformé')], default='AFFECTE', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_affectation', to='core.depot', verbose_name='Dépôt source')),
                ('dotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_affectation', to='purchasing.dotation', verbose_name='Dotation source')),
                ('ligne_dotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiche_affectation', to='purchasing.lignedotation', verbose_name='Ligne de dotation')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_affectation', to='catalog.matiere', verbose_name='Matière')),
                ('mouvement_stock', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiche_affectation', to='inventory.mouvementstock', verbose_name='Mouvement de stock')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_affectation', to='core.service', verbose_name='Service bénéficiaire')),
            ],
            options={
                'verbose_name': "Fiche d'affectation",
                'verbose_name_plural': "Fiches d'affectation",
                'ordering': ['-date_affectation', '-id'],
            },
        ),
    ]
