# Generated by Django 5.2.7 on 2025-12-17 14:03

import django.db.models.deletion
import django.utils.timezone
import purchasing.models.achat
import purchasing.models.don
import purchasing.models.retour_pret
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField(default=django.utils.timezone.now)),
                ('numero_facture', models.CharField(blank=True, default='', max_length=80)),
                ('fichier_facture', models.FileField(blank=True, null=True, upload_to=purchasing.models.achat._upload_facture_path)),
                ('code', models.CharField(blank=True, default='', max_length=40, unique=True)),
                ('tva_active', models.BooleanField(default=False)),
                ('total_ht', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('total_tva', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('total_ttc', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='core.depot')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='core.fournisseur')),
            ],
            options={
                'ordering': ['-date_achat', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('numero_piece', models.CharField(blank=True, default='', max_length=80)),
                ('fichier_piece', models.FileField(blank=True, null=True, upload_to=purchasing.models.don._upload_piece_path)),
                ('code', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('total_valeur', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dons', to='core.depot')),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dons', to='core.donateur')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date_don', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('prix_unitaire', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('total_ligne_ht', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('appreciation', models.CharField(blank=True, default='', max_length=255)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='purchasing.achat')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_achat', to='catalog.matiere')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LigneDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('prix_unitaire', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('total_ligne', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('observation', models.CharField(blank=True, default='', max_length=255)),
                ('don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='purchasing.don')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_don', to='catalog.matiere')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pret', models.DateField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('est_clos', models.BooleanField(default=False)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to='core.depot')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prets', to='core.service')),
            ],
            options={
                'verbose_name': 'Prêt (sortie)',
                'verbose_name_plural': 'Prêts (sorties)',
                'ordering': ['-date_pret', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LignePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('observation', models.CharField(blank=True, default='', max_length=255)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_pret', to='catalog.matiere')),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='purchasing.pret')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RetourFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retour', models.DateField(default=django.utils.timezone.now)),
                ('code', models.CharField(blank=True, default='', max_length=40, unique=True)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='core.depot')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='core.fournisseur')),
            ],
            options={
                'verbose_name': 'Retour fournisseur',
                'verbose_name_plural': 'Retours fournisseurs',
                'ordering': ['-date_retour', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('ligne_achat_origine', models.ForeignKey(blank=True, help_text="Optionnel : si renseigné, la valorisation prend le PU de l'achat d'origine.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.ligneachat')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_retour', to='catalog.matiere')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='purchasing.retourfournisseur')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RetourPret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retour', models.DateField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('numero_piece', models.CharField(blank=True, default='', max_length=80)),
                ('fichier_piece', models.FileField(blank=True, null=True, upload_to=purchasing.models.retour_pret._upload_piece_path)),
                ('code', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('total_qte', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='purchasing.pret')),
            ],
            options={
                'verbose_name': 'Retour de prêt (entrée)',
                'verbose_name_plural': 'Retours de prêt (entrées)',
                'ordering': ['-date_retour', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneRetourPret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('observation', models.CharField(blank=True, default='', max_length=255)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_retour_pret', to='catalog.matiere')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_retour_pret', to='purchasing.retourpret')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
