# Generated by Django 5.2.7 on 2025-12-18 10:33

import django.db.models.deletion
import django.utils.timezone
import purchasing.models.external_stock_entry
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0002_externalsource'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('document_number', models.CharField(blank=True, default='', max_length=80)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=purchasing.models.external_stock_entry.upload_external_entry_file)),
                ('comment', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=60, unique=True)),
                ('total_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_entries', to='core.depot')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='core.externalsource')),
            ],
            options={
                'verbose_name': 'External stock entry',
                'verbose_name_plural': 'External stock entries',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalStockEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('total_line', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.externalstockentry')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_entry_lines', to='catalog.matiere')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
