# Generated by Django 5.2.7 on 2025-12-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Ex: MOB, INF…', max_length=16, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ComptePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.PositiveSmallIntegerField(editable=False, unique=True, verbose_name='PIN principal')),
                ('code', models.CharField(editable=False, max_length=2, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('groupe', models.CharField(choices=[('G1', '1er groupe (codes 10, 11, 12, …)'), ('G2', '2e groupe (codes 20, 21, 22, …)')], max_length=2, verbose_name='Groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Compte principal',
                'verbose_name_plural': 'Comptes principaux',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompteDivisionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.PositiveSmallIntegerField(editable=False, verbose_name='PIN divisionnaire (local au principal)')),
                ('code', models.CharField(editable=False, max_length=5, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('compte_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisionnaires', to='catalog.compteprincipal', verbose_name='Compte principal')),
            ],
            options={
                'verbose_name': 'Compte divisionnaire',
                'verbose_name_plural': 'Comptes divisionnaires',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Ex: BURE, ORDI…', max_length=20, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sous_categories', to='catalog.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Sous-catégorie',
                'verbose_name_plural': 'Sous-catégories',
                'ordering': ['categorie__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SousCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.PositiveSmallIntegerField(editable=False, verbose_name='PIN sous-compte (local au divisionnaire)')),
                ('code', models.CharField(editable=False, max_length=8, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('compte_divisionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sous_comptes', to='catalog.comptedivisionnaire', verbose_name='Compte divisionnaire')),
            ],
            options={
                'verbose_name': 'Sous-compte',
                'verbose_name_plural': 'Sous-comptes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_court', models.CharField(help_text='Ex: ORD, BURE, LED20', max_length=12, unique=True, verbose_name='Code matière (court)')),
                ('designation', models.CharField(max_length=200, verbose_name='Libellé / Désignation')),
                ('type_matiere', models.CharField(choices=[('consommable', 'Consommable'), ('reutilisable', 'Réutilisable')], default='reutilisable', help_text='Permet de distinguer les biens durables des consommables.', max_length=20, verbose_name='Type de matière')),
                ('seuil_min', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Seuil minimum')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('est_stocke', models.BooleanField(default=False, help_text='Coché automatiquement après l’enregistrement du stock initial.', verbose_name='Est stocké (initial saisi)')),
                ('categorie', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='catalog.categorie', verbose_name='Catégorie')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='core.unite', verbose_name='Unité')),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='catalog.souscategorie', verbose_name='Sous-catégorie')),
                ('sous_compte', models.ForeignKey(help_text='Sous-compte d’imputation comptable de cette matière.', on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='catalog.souscompte', verbose_name='Sous-compte')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['code_court'],
            },
        ),
        migrations.AddConstraint(
            model_name='comptedivisionnaire',
            constraint=models.UniqueConstraint(fields=('compte_principal', 'pin'), name='uniq_divisionnaire_pin_par_principal'),
        ),
        migrations.AddConstraint(
            model_name='souscategorie',
            constraint=models.UniqueConstraint(fields=('categorie', 'libelle'), name='uniq_souscat_categorie_libelle'),
        ),
        migrations.AddConstraint(
            model_name='souscompte',
            constraint=models.UniqueConstraint(fields=('compte_divisionnaire', 'pin'), name='uniq_souscompte_pin_par_divisionnaire'),
        ),
    ]
